### ISSUE TITLE
inter is not better than intra

### ISSUE THREAD

**Issue by unicorneeee** [WowCZ/LongMIT#7]
Hello, I hope this message find u well.
I download the LongMIT data in Oct 11 and 17 .
I find the original version 1 data contain both the inter and intra.
The version 2 (nowadays) data only contain the inter.
The peformers of the models which are respectively used inter and intra  to finetune the qwen2.5-base is similar, even the performer of the model used intra is better in the benchmark Loong,Longbench-chat,LoogGLE.
Why this issue happened? Could U please share your test code and test data in the paper? 
Best wishes.

**Comment by WowCZ** [comment]
Sorry to reply late and thanks for interests. In the version 1, the language and the type are both wrong, where only contains one langauge and one context type. We fixed this in version 2 (latest) with two different langauges and three context types. We have not validated our datasets on the Qwen2.5-base. We also didn't test our datatsets on different context types respectively. Because our dataset is QA-only, it is better to focus on the performance on QA tasks.
